### ISSUE TITLE
Error handling request

### ISSUE THREAD

**Issue by L3H0** [YeonV/ledfxrm#4] opened 2020-12-03 13:21 UTC
Hello, 
I have problem when adding your component to my HA instance.
My LedFX is in docker container on Synology.
This is the log:

> Logger: aiohttp.server
Source: custom_components/ledfxrm/config_flow.py:166
First occurred: 14:06:57 (14 occurrences)
Last logged: 14:17:42
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/ledfxrm/config_flow.py", line 51, in async_step_user
    name, version = await self.get_rest_status(
  File "/config/custom_components/ledfxrm/config_flow.py", line 166, in get_rest_status
    rest_info = await resp.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1099, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://192.168.x.x:9999/api/info')

This is the response from API:

> {"url": "http://0.0.0.0:8888", "name": "LedFx Controller", "version": "0.7", "debug_mode": true}

**Comment by YeonV** [comment] 2020-12-08 12:50
Hey there,
please use a newer version of ledfx.

Duplicate of #1 

> Requirements: LedFx > v0.7

maybe the "greater than"-symbol is not enough. i should replace it with a min-version

EDIT: Changed Readme

**Closed as completed** 2020-12-08 12:58 UTC
